# Sturgeon project configuration
paths:
  utils: "/home/prom/sturgeon_v2/utils"
  r_script: "/home/prom/sturgeon_v2/utils/CNV_plot.R"
  bam_input: "/home/prom/sturgeon_v2/bam_pass"
  sturgeon_script: "/home/prom/sturgeon_v2/sturgeon_P2.sh"
  conf_time_plot: "/home/prom/sturgeon_v2/utils/plot.py"
  results_dir: "/home/prom/sturgeon_v2/sturgeon_results"
  script_lock: "/home/prom/sturgeon_v2/script.lock"
  model: " /home/prom/sturgeon_v2/include/models/general.zip"
  model_v2: "/home/prom/sturgeon_v2/cns-v2.zip"
  shutdown_file: "/home/prom/sturgeon_v2/shutdown.flag"
logging:
  log_level: "INFO"
barcode: 18
freq: 1
gridion: False
sturgeon_V2: False
gui_activated: False