# Sturgeon project configuration
paths:
  utils: "/home/prom/sturgeon/utils"
  r_script: "/home/prom/sturgeon/utils/CNV_plot.R"
  bam_input: "/home/prom/sturgeon/bam_pass"
  sturgeon_script: "/home/prom/sturgeon/sturgeon_P2.sh"
  results_dir: "/home/prom/sturgeon/sturgeon_results"
  script_lock: "/home/prom/sturgeon/script.lock"
  model: "/home/prom/sturgeon/sturgeon/include/models/general.zip"
  shutdown_file: "/home/prom/sturgeon/shutdown.flag"
logging:
  log_level: "INFO"
barcode: 18
freq: 1
gridion: False